### ISSUE TITLE
Update Method,  Fuse Error

### ISSUE THREAD

**Issue by frh3ddy** [Syncano/syncano-js#119]
When I try to call the update method in Fuse. it gives me an error.  HTTP  Method not Supported

**Comment by MariuszWisniewski** [comment]
Thanks for the info, we'll look into that.

**Comment by dancio** [comment]
it's all about `PATCH` request:

```
> System.NotSupportedException: HTTP method not supported.
```

which seams to be not supported, I'll provide fix asap :)

**Comment by frh3ddy** [comment]
Thanks Dancio I really appreciate it.

**Comment by MariuszWisniewski** [comment]
@frh3ddy It seems like Fuse environment doesn't allow us to make PATCH calls to our servers. We're looking into that, and we will be working on the workaround.

**Comment by MariuszWisniewski** [comment]
@frh3ddy We got information from Fuse it was fixed and will be available in next release: https://www.fusetools.com/community/forums/bug_reports/syncano_http_method_not_supported . If it doesn't help, feel free to reopen.
