### ISSUE TITLE
React native compatibility

### ISSUE THREAD

**Issue by farwayer** [Syncano/syncano-js#155]
I fixed most critical issue with #154. For now I can use only `syncano.min.js` version from `dist/`. All other non-uglified versions is broken (dependencies etc.)
As I know you are using react for admin front end. Something like official support (or even binding) for react and react-native will be nice (as Firebase done with reactfire).

**Comment by dancio** [comment]
We will be releasing new fix for react native on Tuesday :) Check #160

**Comment by dancio** [comment]
From version 1.0.3 we have support for React Native :)
