### ISSUE TITLE
instance scope with minified JS gives error

### ISSUE THREAD

**Issue by jhishan** [Syncano/syncano-js#18]
traceback

Uncaught TypeError: Cannot read property '1' of null(anonymous function) @ syncano.min.js:57465Pn @ lodash.min.js:9(anonymous function) @ lodash.min.js:30294.f @ syncano.min.js:57464295.s @ syncano.min.js:57718c @ syncano.min.js:57685Todos.TodosController.Ember.ArrayController.extend.actions.createTodo @ todos_controller.js:8Mixin.create.send @ ember.js:29076Mixin.create.triggerAction @ ember.js:32994View.extend.sendAction @ ember.js:41355sendAction @ ember.js:38654Mixin.create.insertNewline @ ember.js:38533Mixin.create.interpretKeyEvents @ ember.js:38508Mixin.create.keyUp @ ember.js:38615EmberObject.extend.trigger @ ember.js:41899superWrapper @ ember.js:18158merge.handleEvent @ ember.js:43053CoreView.extend.handleEvent @ ember.js:45400Backburner.run @ ember.js:200Backburner.join @ ember.js:223run.join @ ember.js:16759__exports__.default.EmberObject.extend._bubbleEvent @ ember.js:39393(anonymous function) @ ember.js:39344jQuery.event.dispatch @ jquery.js:4430jQuery.event.add.elemData.handle @ jquery.js:4116

Code in controller file 

``` javascript
var account = new Syncano({apiKey: "someapikey", instance: "todolist"});
```

More code in index.html file

``` javascript
<script type="text/javascript" src="bower_components/bluebird/js/browser/bluebird.min.js"></script>
<script type="text/javascript" src="bower_components/lodash/lodash.min.js"></script>
<script type="text/javascript" src="bower_components/syncano/dist/syncano.min.js"></script>
```

**Comment by kellyjandrews** [comment]
Thanks @jhishan - I've narrowed it down to the implementation of the `Instance` object here 

``` js
    if (opts && opts.accountKey) {
      objArr = [Admin, ApiKey, Channel, Class, CodeBox, Invitation, Group, Schedule, Trigger, WebHook, User];
    } else {
      objArr = [Channel, Class, Group, User];
    }

    _.forEach(objArr, function(Obj) {
      var name = Obj.toString().match(/^function\s*([^\s(]+)/)[1]; //this is the offending line
      self[name.toLowerCase()] = classBuilder(Obj, opts);
    });
```

Works great when not minified - but need to implement this differently to avoid the issue with min versions. Thanks!
