### ISSUE TITLE
Support for running public webhooks

### ISSUE THREAD

**Issue by MariuszWisniewski** [Syncano/syncano-js#23]
I have a public webhook and I would like to run it. Would be great if I could do it using Syncano's library, which would be easier than implementing running a link from scratch (could be similar to how it's done in jQuery).

**Comment by kellyjandrews** [comment]
Why not just use jQuery then?  That library would do a better job at running an ajax call - and not sure it's something we really need to build.  I don't think it would be from scratch either using something like jQuery - and if we built it the same way - then it would be the same amount of effort. 

I don't think we could make it any easier, except they don't have to include jQuery - but chances are good they will have something to make HTTP calls already in their library - no need to bloat this with another version of that functionality.

**Comment by MariuszWisniewski** [comment]
Maybe. But we already have something for making requests inside a library. And response is also standardized when it comes to `stdout` and `stderr` - so we could parse it to provide better user experience.
I feel that if writing custom code for running a public webhook is something everyone will have to do (since it's not possible to run a CodeBox without Account Key) - we should help with that.

I agree that we shouldn't bloat libraries with not needed code, but I think the goal when using Syncano is to use Syncano only - so in most cases, I think it's possible users wouldn't have anything else to do http calls - why would they, if they store everything on Syncano?

**Comment by kellyjandrews** [comment]
We already include the request library - which would allow someone to call any route - so technically it's already there. 

I don't see any need to write a wrapper around it - we can document how to make calls using what's already there - we don't need to write anything new for this.

**Comment by kellyjandrews** [comment]
One last comment - this may eventually be something we do - but as of right now - it's not something that's absolutely required.  We can reevaluate after other priorities are completed.

**Comment by MariuszWisniewski** [comment]
When we encourage people to use CodeBoxes and Webhooks, when we ask them to create custom API, not having any extra support in libraries for it, may not be the right way to go.

**Comment by kellyjandrews** [comment]
I'll reopen this - happy to review any pull requests since I won't be able to get to this soon. Using $.get isn't that difficult - but I understand your point - which is the reason for the comment previous to yours. Maybe @patrickdevivo or @devintyler could help with this one?
