### ISSUE TITLE
Passing custom "baseUrl" when creating a connection doesn't work

### ISSUE THREAD

**Issue by adamwardecki** [Syncano/syncano-js#28]
I'm trying to pass a different domain as an argument when creating a connection to Syncano:

var syncano = new Syncano({baseUrl: 'very.custom.url'});

but it doesn't seem to work. I'm being connected to production environment.

**Comment by kellyjandrews** [comment]
Found the issue - it will be fixed in v0.3.0 which should be available by end of the week.
